FROM nginx:1.12.1

#ADD  nginx.conf      /etc/nginx/nginx.conf
#ADD  conf.d/*    	 /etc/nginx/conf.d/
#RUN  mkdir /nginx/html && mkdir /nginx/logs
#RUN  chown -R www-data.www-data /nginx/html /nginx/logs

VOLUME ["/nginx"]